trigger:
  - main

variables:
  acrName: 'reactfrontedcode'
  containerRegistry: 'reactfrontedcode.azurecr.io'
  imageRepository: 'reactfrontedcode'
  tag: '59'
  vmConnectionName: 'vm-connection'

stages:
- stage: Deploy
  displayName: Deploy to VM
  jobs:
  - job: Deploy
    displayName: Deploy to VM
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: SSH@0
      inputs:
        sshEndpoint: '$(vmConnectionName)'
        runOptions: 'inline'
        inline: |
          # Login to ACR
          az acr login --name $(acrName)
          
          # Pull the latest image
          docker pull $(acrName).azurecr.io/$(imageRepository):$(tag)
          
          # Stop and remove existing container if it exists
          docker stop $(imageRepository) || true
          docker rm $(imageRepository) || true
          
          # Run the new container
          docker run -d \
            --name $(imageRepository) \
            --restart unless-stopped \
            $(acrName).azurecr.io/$(imageRepository):$(tag)